branch-defaults:
  develop:
    environment: djcrossman-battlesnake-api
environment-defaults:
  djcrossman-battlesnake-api:
    branch: null
    repository: null
global:
  application_name: battlesnake-api
  default_ec2_keyname: battlesnake-api
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application